import Head from "next/head";

// import Link from "next/link";
import {
  SiVk,
  SiTelegram,
  SiGithub,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiReact,
  SiRedux,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import logo from "../public/logo.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Arthur Sadreev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className=" bg-gray-300 px-10 dark:bg-gray-900 md:px-20 lg:px-40 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="object-contain h-10 w-10 fill-cyan-500 colorful-shadow-logo user-select">
              <Image
                src={logo}
                alt="logo"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                objectFit="cover"
              />
            </h1>

            <ul className="flex items-center ">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>

              <a
                href="https://kazan.hh.ru/resume/bddc22ccff012764f30039ed1f624a5a735842"
                target="_blank"
                rel="noopener noreferrer"
              >
                <button className="btn btn_hover active:scale-95 user-select ">
                  Resume
                </button>
              </a>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text_h1 user-select text_h1_sm ">Arthur Sadreev</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl user-select">
              Frontend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-black dark:text-gray-200 max-w-xl mx-auto md:text-3xl user-select">
              My skills:
            </p>
            <p className="text-5xl small flex justify-center gap-16 p-3   text-blue-700 rounded-xl  colorful-shadow">
              <SiHtml5 />
              <SiCss3 />
              <SiJavascript />
              <SiTypescript />
              <SiReact />
              <SiRedux />
              <SiTailwindcss />
            </p>
            <p className="text-md py-5 leading-8 text-black dark:text-gray-200 max-w-xl mx-auto md:text-3xl user-select">
              Contact me:
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 dark:text-blue-600">
              <a href="https://vk.com/endo0m" className="icon_blue">
                <SiVk />
              </a>
              <a href="https://t.me/Endoom" className="icon_blue-3xl">
                <SiTelegram />
              </a>
              <a href="https://github.com/Endo0m" className="icon_git">
                <SiGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-tr to-teal-500 from-slate-700 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 img_small_screen">
              <Image src={deved} alt="Me" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="py-10">
          <h1 className="text-3xl py-1 dark:text-white ">Обо мне</h1>
          <div className="text-md py-2 leading-8 text-gray-900 dark:text-gray-200">
            Начинающий Frontend-разработчик. Обучаюсь самостоятельно. Опыта в it
            реального совсем нет. Только демо. Разбираюсь в чужом коде, могу
            писать свой. Высокий уровень знания HTML, CSS(Sass), JavaScript,
            фреймворков и программных платформ React, Tailwind. <br />{" "}
            <span className="orange-text-gradient"> Главное </span> Я
            дисциплинированный, пунктуальный, соблюдаю дедлайны{" "}
            <span className="text-slate-600">
              (для меня сроки это не возможность растянуть, я лучше сделаю
              быстрее и возьмусь за новый проект)
            </span>{" "}
            мне важен результат, я хочу освоить на профессиональном уровне
            Frontend и так же Game development
          </div>
        </section>
        <section className="py-10">
          <div className="user-select">
            <h3 className="text-3xl py-1 dark:text-white ">Портфолио</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              На данный момент в этом разделе находятся только демо. Выполненые
              <span className="text-orange-600 dark:text-teal-500">
                {" "}
                мною.{" "}
              </span>
              Для ознакомления моих{" "}
              <span className="text-orange-600 dark:text-teal-500">
                умений.{" "}
              </span>
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
            </p> */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1  projects">
              <a
                href="https://endo0m.github.io/restoran/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className=" rounded-lg object-fill "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                  alt="project"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 projects ">
              <a
                href="https://endo0m.github.io/dashboard/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-fill"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                  alt="project2"
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1 projects">
              <a
                href="https://endo0m.github.io/luxcars/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-fill"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web3}
                  alt="project3"
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1 projects">
              <Image
                className="rounded-lg object-fill"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="project4"
              />
            </div>
            <div className="basis-1/3 flex-1 projects">
              <Image
                className="rounded-lg object-fill"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="project5"
              />
            </div>
            <div className="basis-1/3 flex-1 projects">
              <Image
                className="rounded-lg object-fill"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="project6"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
